mex -v -O -L.\\ -lqubtree qub_loadTree.cpp treestruct.cpp
mex -v -O -L.\\ -lqubtree qub_saveTree.cpp treestruct.cpp

mex -v -O -L.\\ -LC:\Python23\libs -lqubtree -lqubopt -lpython23 -DQUB_DLL -DWIN32 -DMEX_FCN -Iqubtree -IC:\Shares\Daniel2\qub\qublib -IC:\Shares\Daniel2\qub\qubopt -IC:\Shares\Daniel2\qub\include -IC:\Python23\include -IC:\Shares\Daniel2\qub\_qubtree qub_milOptimize.cpp treestruct.cpp
